# Group Players

A Player represent an online multiplayer Running With Rifles account on ranked servers.

::: note
**Important note**

Players stats are updated daily and **only** concerns official Invasion and WW2 DLCs servers.

Also, stats history is only recorded for the 5000 most experienced players.
:::

## Players [/players/{database}{?start,sort,target,limit}]

+ Parameters
    + database: `invasion` (enum[string]) - The players database.
      + Members
          + `invasion`
          + `pacific`
    + start: `15` (integer, optional)
        Pagination start offset.

        Minimum value: `0`
      + Default: `0`
    + sort: `rank_progression` (optional) - The stat value (or column) on which the player list should be sorted.
      + Members
          + `username`
          + `kills`
          + `deaths`
          + `score`
          + `kd`
          + `time_played`
          + `longest_kill_streak`
          + `targets_destroyed`
          + `vehicles_destroyed`
          + `soldiers_healed`
          + `teamkills`
          + `distance_moved`
          + `shots_fired`
          + `throwables_thrown`
          + `rank_progression`
      + Default: `score`
    + target: `EPOCDOTFR` (optional) - A player username that should be highlighted.
    + limit: `25` (integer, optional)
        Number of players to return.

        Minimum value: `1`

        Maximum value: `100`
      + Default: `15`

### Get a list of Players [GET]

Return a list of Players (leaderboard). The list may be optionally filtered or sorted.

::: note
#### Server-side caching

This resource has a cache lifetime of **1 hour**.
:::

+ Request

    + Headers

            Authorization: Token {Your Personal Access Token}

+ Response 200 (application/json)

    + Attributes (array[Player List Object], fixed-type)

+ Response 400 (application/json)

    One or more arguments are (is) invalid. Check the error message(s) for more information.

    + Attributes (Error Response, fixed-type)

+ Response 403 (application/json)

    Invalid Personal Access Token or Personal Access Token not provided.

    + Attributes (Error Response, fixed-type)

+ Response 404 (application/json)

    Only if the `target` parameter was provided: the given player username doesn't exist.

    + Attributes (Error Response, fixed-type)

+ Response 503 (application/json)

    Maintenance in progress.

    + Attributes (Error Response, fixed-type)

## Player [/players/{database}/{username}{?date}]

+ Parameters
    + database: `invasion` (enum[string]) - The player database.
      + Members
          + `invasion`
          + `pacific`
    + username: `EPOCDOTFR` - The player username.
    + date: `2018-11-30` (optional)

        [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date for which to retrieve the stats for.

        Note the player must be part of the 5000 most experienced players for its stats history to be recorded.

### Get a specific Player [GET]

Return the Player corresponding to the given database / player username couple.

::: note
#### Server-side caching

This resource has a cache lifetime of **1 hour**.
:::

+ Request

    + Headers

            Authorization: Token {Your Personal Access Token}

+ Response 200 (application/json)

    + Attributes (Player Full Object, fixed-type)

+ Response 400 (application/json)

    One or more arguments are (is) invalid. Check the error message(s) for more information.

    + Attributes (Error Response, fixed-type)

+ Response 404 (application/json)

    The Player wasn't found or, only when the `date` parameter is provided: no stats found for this player (although he's eligible for stats history).

    + Attributes (Error Response, fixed-type)

+ Response 403 (application/json)

    Invalid Personal Access Token or Personal Access Token not provided.

    + Attributes (Error Response, fixed-type)

+ Response 412 (application/json)

    If the `date` parameter is provided: the Player isn't eligible for stats history (5000 most experienced players only).

    + Attributes (Error Response, fixed-type)

+ Response 503 (application/json)

    Maintenance in progress.

    + Attributes (Error Response, fixed-type)

## Player [/players/{database}/{username}/stats-history{?page,limit}]

+ Parameters
    + database: `invasion` (enum[string]) - The player database.
      + Members
          + `invasion`
          + `pacific`
    + username: `EPOCDOTFR` - The player username.
    + page: `1` (integer, optional)
        Minimum value: `1`
      + Default: `1`
    + limit: `25` (integer, optional)
        Number of stats row to return.

        Minimum value: `1`

        Maximum value: `100`
      + Default: `15`

### Get stats history [GET]

Return stats history corresponding to the given database / player username couple.

Available only for the 5000 most experienced players.

+ Request

    + Headers

            Authorization: Token {Your Personal Access Token}

+ Response 200 (application/json)

    + Attributes (array[Player Stats History Object], fixed-type)

+ Response 400 (application/json)

    One or more arguments are (is) invalid. Check the error message(s) for more information.

    + Attributes (Error Response, fixed-type)

+ Response 404 (application/json)

    The Player wasn't found.

    + Attributes (Error Response, fixed-type)

+ Response 403 (application/json)

    Invalid Personal Access Token or Personal Access Token not provided.

    + Attributes (Error Response, fixed-type)

+ Response 412 (application/json)

    The Player isn't eligible for stats history (5000 most experienced players only).

    + Attributes (Error Response, fixed-type)

+ Response 503 (application/json)

    Maintenance in progress.

    + Attributes (Error Response, fixed-type)