### Database Object

  + `id`: `invasion` (nullable) - Database ID. `null` if not a ranked server or not a player on ranked servers
    + Default: `null`
  + `name`: `Invasion` (nullable) - Database name. `null` if not a ranked server or not a player on ranked servers
    + Default: `null`