### Database Object

  + `id`: `invasion` - The database ID
  + `name`: `Invasion` - The database name

### Error Response

  + message: `Example error message` (required) - The error message explaining what happened