### Database Object

  + `id`: `invasion` (nullable) - Database ID. `null` if not a ranked server or not a ranked servers player
    + Default: `null`
  + `name`: `Invasion` (nullable) - Database name. `null` if not a ranked server or not a ranked servers player
    + Default: `null`