### Map Counters Object

  + `players` (required) - Player counts
      + `total`: `85` (number, required) - Total number of people playing RWR
      + `online`: `32` (number, required) - Number of people playing RWR multiplayer online
  + `servers` (required) - Player counts
      + `total`: `22` (number, required) - Total number of public RWR servers
      + `active`: `7` (number, required) - Number of active (non-empty) public RWR servers
