### Player Simple Object

  + `username`: `EPOCDOTFR` (required) - Player username
  + `url`: `https://rwrstats.com/players/invasion/EPOCDOTFR` (nullable) - RWRS player profile page URL. `null` if the player isn't a ranked profile
    + Default: `null`
  + `is_rwrs_creator`: `true` (boolean, required) - Whether this player is the creator of RWRS
  + `is_contributor`: `false` (boolean, required) - Whether this player contributed in a way or another to RWRS
  + `is_rwr_dev`: `false` (boolean, required) - Whether this player is one of the RWR developers
  + `is_ranked_servers_admin`: `false` (boolean, required) - Whether this player is admin on ranked (official) servers