### Player Simple Object

  + `username`: `EPOCDOTFR` (required) - Player username
  + `url`: `https://rwrstats.com/players/invasion/EPOCDOTFR` - RWRS player profile page URL. `null` if the player isn't playing on a ranked (official) server
    + Default: `null`
