## Data Structures

### Server Map Simple Object

  + `name`: `Railroad Gap` (required) - Map name. If unknown, its internal ID will be used

### Server Map Full Object (Server Map Simple Object)

  + `preview_image_url`: `https://rwrstats.com/images/maps/preview/vanilla.winter/map4.png` - Map preview image URL. `null` if none available
    + Default: `null`

### Server Location Object

  + `name`: `Frankfurt am Main, Germany` - City name (if available) + country name of the server location. `null` if unknown
    + Default: `null`
  + `country_code`: `de` - ISO 3166-1 alpha-2 country code of the server location. `null` if unknown
    + Default: `null`

### Server Players Simple Object

  + `current`: `20` (number, required) - Number of current players
  + `max`: `24` (number, required) - Maximum allowed number of players
  + `free`: `4` (number, required) - Number of free player slots

### Server Players Full Object (Server Players Simple Object)

  + `list`: `EPOCDOTFR`, `JACKMAYOL`, `PASIK` (array[string], required) - List of current players

### Server Simple Object

  + `name`: `InvasionEU2` (required) - Server name
  + `type_name`: `Vanilla` (required) - Server type name (used mod or DLC)
  + `mode_name`: `Coop.` (required) - Server mode name (game mode)
  + `is_ranked`: `true` (boolean, required) - Whether this server is an official one
  + `website_url`: `https://runningwithrifles.com/` - Server website URL. `null` if none
    + Default: `null`
  + `url`: `https://rwrstats.com/servers/31.186.250.67:1235/invasioneu2` (required) - RWRS server web page URL
  + `map` (Server Map Simple Object, required) - Server map
  + `players` (Server Players Simple Object, required) - Server players
  + `location` (Server Location Object, required) - Server location

### Server Full Object (Server Simple Object)

  + `map` (Server Map Full Object, required) - Server map
  + `version`: `1.70.2` (required) - Server game version
  + `database_name`: `Invasion` - Database name. `null` if not a ranked server
    + Default: `null`
  + `mode_name_long`: `Cooperation` (required) - Long server mode name
  + `is_dedicated`: `true` (boolean, required) - Whether this server is a dedicated one
  + `comment`: `Coop campaign` - Server comment. `null` if none
    + Default: `null`
  + `bots`: `104` (number, required) - Number of current bots
  + `players` (Server Players Full Object, required) - Server players

### Error Response

  + message: `Example error message` (required) - The error message explaining what happened