### User Simple Object

  + `id`: `56` (number, required) - RWRS user ID
  + `username`: `Epoc` (required) - The user nickname (as provided by Steam)
  + `url`: `https://rwrstats.com/users/56/epoc` (required) - RWRS user profile page URL
  + `small_avatar_url`: `https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/18/18a19ee73965fb3b92f39db8a307df80f5624122.jpg` (nullable) - User small avatar (as provided by Steam). 32x32 pixels
    + Default: `null`
  + `large_avatar_url`: `https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/18/18a19ee73965fb3b92f39db8a307df80f5624122_full.jpg` (nullable) - User large avatar (as provided by Steam). 184x184 pixels
    + Default: `null`

### User Full Object (User Simple Object)

  + `registered_at`: `2019-02-22T10:46:00+00:00` (required) - [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date / time when user registered on RWRS
  + `accounts` (array[Player Intermediate Object], fixed-type) - List of linked RWR accounts
