SECRET_KEY = 'secretkeyhere'
DEBUG = False
LOGGER_HANDLER_POLICY = 'production'
GAUGES_SITE_ID = None
CACHE_THRESHOLD = 200
SERVERS_CACHE_TIMEOUT = 60
PLAYERS_CACHE_TIMEOUT = 60 * 60
GRAPHS_DATA_CACHE_TIMEOUT = 60 * 15
