"""empty message

Revision ID: 05dbe0cada64
Revises: f34415dc50d7
Create Date: 2022-04-29 14:12:11.078764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05dbe0cada64'
down_revision = 'f34415dc50d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rwr_accounts', sa.Column('pending_delete', sa.Boolean(), nullable=False, default=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rwr_accounts', 'pending_delete')
    # ### end Alembic commands ###
