"""empty message

Revision ID: 0c6c5e50c10a
Revises:
Create Date: 2018-07-23 15:40:12.345079

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0c6c5e50c10a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rwr_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('INVASION', 'PACIFIC', name='rwraccounttype'), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('type_username_idx', 'rwr_accounts', ['type', 'username'], unique=False)
    op.create_table('rwr_root_servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('UP', 'DOWN', name='rwrrootserverstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('host_idx', 'rwr_root_servers', ['host'], unique=False)
    op.create_table('servers_player_count',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('measured_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ip_port_idx', 'servers_player_count', ['ip', 'port'], unique=False)
    op.create_table('steam_players_count',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('measured_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('INTEGER', 'FLOAT', 'STRING', 'BOOL', 'ARROW', 'JSON', name='variabletype'), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rwr_account_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('leaderboard_position', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('time_played', sa.Integer(), nullable=False),
    sa.Column('longest_kill_streak', sa.Integer(), nullable=False),
    sa.Column('targets_destroyed', sa.Integer(), nullable=False),
    sa.Column('vehicles_destroyed', sa.Integer(), nullable=False),
    sa.Column('soldiers_healed', sa.Integer(), nullable=False),
    sa.Column('teamkills', sa.Integer(), nullable=False),
    sa.Column('distance_moved', sa.Float(), nullable=False),
    sa.Column('shots_fired', sa.Integer(), nullable=False),
    sa.Column('throwables_thrown', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=32), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('rwr_account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rwr_account_id'], ['rwr_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('created_at_idx', 'rwr_account_stats', ['created_at'], unique=False)
    op.create_index('hash_idx', 'rwr_account_stats', ['hash'], unique=False)
    op.create_index('rwr_account_id_idx', 'rwr_account_stats', ['rwr_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('rwr_account_id_idx', table_name='rwr_account_stats')
    op.drop_index('hash_idx', table_name='rwr_account_stats')
    op.drop_index('created_at_idx', table_name='rwr_account_stats')
    op.drop_table('rwr_account_stats')
    op.drop_table('variables')
    op.drop_table('steam_players_count')
    op.drop_index('ip_port_idx', table_name='servers_player_count')
    op.drop_table('servers_player_count')
    op.drop_index('host_idx', table_name='rwr_root_servers')
    op.drop_table('rwr_root_servers')
    op.drop_index('type_username_idx', table_name='rwr_accounts')
    op.drop_table('rwr_accounts')
    # ### end Alembic commands ###
