"""empty message

Revision ID: 36f2149d6667
Revises: 7fe1b79f7f8e
Create Date: 2019-02-22 13:55:55.096480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f2149d6667'
down_revision = '7fe1b79f7f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_ads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('OFFER', 'REQUEST', name='marketadtype'), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CONCLUDED', 'CANCELLED', name='marketadstatus'), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('rwr_account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rwr_account_id'], ['rwr_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('created_at_idx', 'market_ads', ['created_at'], unique=False)
    op.create_index('rwr_account_id_idx', 'market_ads', ['rwr_account_id'], unique=False)
    op.create_index('type_status_idx', 'market_ads', ['type', 'status'], unique=False)
    op.add_column('rwr_accounts', sa.Column('claim_initiated_by_user_id', sa.Integer(), nullable=True))
    op.add_column('rwr_accounts', sa.Column('claim_possible_until', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    op.add_column('rwr_accounts', sa.Column('claimed_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    op.add_column('rwr_accounts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rwr_accounts', 'users', ['claim_initiated_by_user_id'], ['id'])
    op.create_foreign_key(None, 'rwr_accounts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rwr_accounts', type_='foreignkey')
    op.drop_constraint(None, 'rwr_accounts', type_='foreignkey')
    op.drop_column('rwr_accounts', 'user_id')
    op.drop_column('rwr_accounts', 'claimed_at')
    op.drop_column('rwr_accounts', 'claim_possible_until')
    op.drop_column('rwr_accounts', 'claim_initiated_by_user_id')
    op.drop_index('type_status_idx', table_name='market_ads')
    op.drop_index('rwr_account_id_idx', table_name='market_ads')
    op.drop_index('created_at_idx', table_name='market_ads')
    op.drop_table('market_ads')
    # ### end Alembic commands ###
