"""empty message

Revision ID: 68f333014dfa
Revises: 05dbe0cada64
Create Date: 2022-09-08 17:28:55.081828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f333014dfa'
down_revision = '05dbe0cada64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rwr_account_stats') as batch_op:
        batch_op.drop_column('leaderboard_position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rwr_account_stats', sa.Column('leaderboard_position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###
