"""empty message

Revision ID: 74efc7509253
Revises: 0c6c5e50c10a
Create Date: 2018-11-21 16:00:21.395539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74efc7509253'
down_revision = '0c6c5e50c10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rwr_account_stats', sa.Column('promoted_to_rank_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rwr_account_stats', 'promoted_to_rank_id')
    # ### end Alembic commands ###
