"""empty message

Revision ID: 78c86db5bdb6
Revises: 0c6c5e50c10a
Create Date: 2018-12-14 10:02:46.775510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78c86db5bdb6'
down_revision = '0c6c5e50c10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('host_idx', table_name='rwr_root_servers')
    op.drop_table('rwr_root_servers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rwr_root_servers',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('host', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.ENUM('UP', 'DOWN'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('host_idx', 'rwr_root_servers', ['host'], unique=False)
    # ### end Alembic commands ###
