"""empty message

Revision ID: 7e5c9bf60c58
Revises: 78c86db5bdb6
Create Date: 2019-01-30 14:19:15.418379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5c9bf60c58'
down_revision = '78c86db5bdb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rwr_account_stats', sa.Column('promoted_to_rank_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rwr_account_stats', 'promoted_to_rank_id')
    # ### end Alembic commands ###
