"""empty message

Revision ID: 7fe1b79f7f8e
Revises: 7e5c9bf60c58
Create Date: 2019-02-22 11:46:19.895300

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '7fe1b79f7f8e'
down_revision = '7e5c9bf60c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('steam_id', sa.String(length=17), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('small_avatar_url', sa.String(length=255), nullable=True),
    sa.Column('large_avatar_url', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('is_profile_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('last_login_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steam_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
