"""empty message

Revision ID: 8e466ee6fddc
Revises: 05dbe0cada64
Create Date: 2023-04-11 18:19:21.943607

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '8e466ee6fddc'
down_revision = '05dbe0cada64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_last_called_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_last_called_at')
    # ### end Alembic commands ###
