"""empty message

Revision ID: 950f85a369b7
Revises: da8b5f9c66ef
Create Date: 2019-04-18 17:48:54.744703

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '950f85a369b7'
down_revision = 'da8b5f9c66ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pat', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.create_index('pat_idx', 'users', ['pat'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('pat_idx', table_name='users')
    op.drop_column('users', 'pat')
    # ### end Alembic commands ###
