"""empty message

Revision ID: 9ad3f703a180
Revises: f25d06f0afbd
Create Date: 2023-11-27 13:47:59.574287

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '9ad3f703a180'
down_revision = 'f25d06f0afbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rwr_accounts', sa.Column('last_seen_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rwr_accounts', 'last_seen_at')
    # ### end Alembic commands ###
