"""empty message

Revision ID: 9efec456a057
Revises:
Create Date: 2018-01-10 13:38:57.347862

"""
from alembic import op
from sqlalchemy_utils import ArrowType
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9efec456a057'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_servers_player_count():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_servers_player_count():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_steam_players_count():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'steam_players_count',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('measured_at', ArrowType(), nullable=False),
        sa.Column('count', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_steam_players_count():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steam_players_count')
    # ### end Alembic commands ###
