"""empty message

Revision ID: bd913507d21d
Revises: f9e51c1c0b89
Create Date: 2018-08-04 15:07:01.961545

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'bd913507d21d'
down_revision = 'f9e51c1c0b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_ads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('OFFER', 'REQUEST', name='marketadtype'), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CONCLUDED', 'CANCELLED', name='marketadstatus'), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('rwr_account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rwr_account_id'], ['rwr_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('rwr_account_id_idx', 'market_ads', ['rwr_account_id'], unique=False)
    op.create_index('type_idx', 'market_ads', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('type_idx', table_name='market_ads')
    op.drop_index('rwr_account_id_idx', table_name='market_ads')
    op.drop_table('market_ads')
    # ### end Alembic commands ###
