"""empty message

Revision ID: da8b5f9c66ef
Revises: 7fe1b79f7f8e
Create Date: 2019-02-25 12:41:52.173564

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'da8b5f9c66ef'
down_revision = '7fe1b79f7f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rwr_accounts', sa.Column('claim_initiated_by_user_id', sa.Integer(), nullable=True))
    op.add_column('rwr_accounts', sa.Column('claim_possible_until', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    op.add_column('rwr_accounts', sa.Column('claimed_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    op.add_column('rwr_accounts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rwr_accounts', 'users', ['claim_initiated_by_user_id'], ['id'])
    op.create_foreign_key(None, 'rwr_accounts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rwr_accounts', type_='foreignkey')
    op.drop_constraint(None, 'rwr_accounts', type_='foreignkey')
    op.drop_column('rwr_accounts', 'user_id')
    op.drop_column('rwr_accounts', 'claimed_at')
    op.drop_column('rwr_accounts', 'claim_possible_until')
    op.drop_column('rwr_accounts', 'claim_initiated_by_user_id')
    # ### end Alembic commands ###
