"""empty message

Revision ID: e30c603a00e9
Revises: da8b5f9c66ef
Create Date: 2019-02-25 12:57:08.076539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30c603a00e9'
down_revision = 'da8b5f9c66ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_ads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('OFFER', 'REQUEST', name='marketadtype'), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CONCLUDED', 'CANCELLED', name='marketadstatus'), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('rwr_account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rwr_account_id'], ['rwr_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('created_at_idx', 'market_ads', ['created_at'], unique=False)
    op.create_index('rwr_account_id_idx', 'market_ads', ['rwr_account_id'], unique=False)
    op.create_index('type_status_idx', 'market_ads', ['type', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('type_status_idx', table_name='market_ads')
    op.drop_index('rwr_account_id_idx', table_name='market_ads')
    op.drop_index('created_at_idx', table_name='market_ads')
    op.drop_table('market_ads')
    # ### end Alembic commands ###
