"""empty message

Revision ID: f34415dc50d7
Revises: 08f64fd3ef85
Create Date: 2022-03-09 13:01:03.027304

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy import Constraint

# revision identifiers, used by Alembic.
revision = 'f34415dc50d7'
down_revision = '08f64fd3ef85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rwr_accounts') as batch_op:
        batch_op.drop_constraint(Constraint('rwr_accounts_ibfk_1'))
        batch_op.drop_constraint(Constraint('rwr_accounts_ibfk_2'))

        batch_op.drop_column('claim_initiated_by_user_id')
        batch_op.drop_column('claimed_at')
        batch_op.drop_column('claim_possible_until')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rwr_accounts', sa.Column('claim_initiated_by_user_id', sa.Integer(), nullable=True))
    op.add_column('rwr_accounts', sa.Column('claim_possible_until', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    op.add_column('rwr_accounts', sa.Column('claimed_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))

    op.create_foreign_key(None, 'rwr_accounts', 'users', ['claim_initiated_by_user_id'], ['id'])
    op.create_foreign_key(None, 'rwr_accounts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
