"""empty message

Revision ID: f9e51c1c0b89
Revises: 0c6c5e50c10a
Create Date: 2018-07-24 13:55:09.711582

"""
from sqlalchemy.dialects import mysql
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f9e51c1c0b89'
down_revision = '0c6c5e50c10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('steam_id', mysql.INTEGER(display_width=17), nullable=False),
    sa.Column('steam_username', sa.String(length=80), nullable=False),
    sa.Column('small_avatar_url', sa.String(length=255), nullable=True),
    sa.Column('large_avatar_url', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('last_login_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steam_id')
    )
    op.add_column('rwr_accounts', sa.Column('claim_initiated_by_user_id', sa.Integer(), nullable=True))
    op.add_column('rwr_accounts', sa.Column('claim_possible_until', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    op.add_column('rwr_accounts', sa.Column('claimed_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    op.add_column('rwr_accounts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rwr_accounts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'rwr_accounts', 'users', ['claim_initiated_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rwr_accounts', type_='foreignkey')
    op.drop_constraint(None, 'rwr_accounts', type_='foreignkey')
    op.drop_column('rwr_accounts', 'user_id')
    op.drop_column('rwr_accounts', 'claimed_at')
    op.drop_column('rwr_accounts', 'claim_possible_until')
    op.drop_column('rwr_accounts', 'claim_initiated_by_user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
